services:
  bot:
    build:
      context: ./bot
    container_name: weather-bot
    restart: unless-stopped
    volumes:
      - /.oshkov/weather-bot:/.oshkov/weather-bot

  notifications:
    build:
      context: ./notifications
    container_name: weather-bot-notifications
    restart: unless-stopped
    volumes:
      - /.oshkov/weather-bot:/.oshkov/weather-bot

  redis:
    image: redis:latest
    container_name: weather-bot-redis
    restart: unless-stopped